<?php

namespace Proxies\__CG__\PointWeb\ReferencingBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Referencing extends \PointWeb\ReferencingBundle\Entity\Referencing implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'PointWeb\\ReferencingBundle\\Entity\\Referencing' . "\0" . 'id', '' . "\0" . 'PointWeb\\ReferencingBundle\\Entity\\Referencing' . "\0" . 'title', '' . "\0" . 'PointWeb\\ReferencingBundle\\Entity\\Referencing' . "\0" . 'h1', '' . "\0" . 'PointWeb\\ReferencingBundle\\Entity\\Referencing' . "\0" . 'h1Title', '' . "\0" . 'PointWeb\\ReferencingBundle\\Entity\\Referencing' . "\0" . 'description', '' . "\0" . 'PointWeb\\ReferencingBundle\\Entity\\Referencing' . "\0" . 'path', '' . "\0" . 'PointWeb\\ReferencingBundle\\Entity\\Referencing' . "\0" . 'online');
        }

        return array('__isInitialized__', '' . "\0" . 'PointWeb\\ReferencingBundle\\Entity\\Referencing' . "\0" . 'id', '' . "\0" . 'PointWeb\\ReferencingBundle\\Entity\\Referencing' . "\0" . 'title', '' . "\0" . 'PointWeb\\ReferencingBundle\\Entity\\Referencing' . "\0" . 'h1', '' . "\0" . 'PointWeb\\ReferencingBundle\\Entity\\Referencing' . "\0" . 'h1Title', '' . "\0" . 'PointWeb\\ReferencingBundle\\Entity\\Referencing' . "\0" . 'description', '' . "\0" . 'PointWeb\\ReferencingBundle\\Entity\\Referencing' . "\0" . 'path', '' . "\0" . 'PointWeb\\ReferencingBundle\\Entity\\Referencing' . "\0" . 'online');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Referencing $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', array($title));

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', array());

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setH1($h1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setH1', array($h1));

        return parent::setH1($h1);
    }

    /**
     * {@inheritDoc}
     */
    public function getH1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getH1', array());

        return parent::getH1();
    }

    /**
     * {@inheritDoc}
     */
    public function setH1Title($h1Title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setH1Title', array($h1Title));

        return parent::setH1Title($h1Title);
    }

    /**
     * {@inheritDoc}
     */
    public function getH1Title()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getH1Title', array());

        return parent::getH1Title();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setPath($path)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPath', array($path));

        return parent::setPath($path);
    }

    /**
     * {@inheritDoc}
     */
    public function getPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPath', array());

        return parent::getPath();
    }

    /**
     * {@inheritDoc}
     */
    public function setOnline($online)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOnline', array($online));

        return parent::setOnline($online);
    }

    /**
     * {@inheritDoc}
     */
    public function getOnline()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOnline', array());

        return parent::getOnline();
    }

}
