<?php

namespace Proxies\__CG__\PointWeb\FicheBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Frais extends \PointWeb\FicheBundle\Entity\Frais implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'autre', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'id', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'matricule', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'startDate', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'endDate', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'updateDate', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'createDate', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'online', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'valide', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'attente', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'refuser', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'qtNuit', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'qtRepas', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'qtKm', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'prixNuit', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'prixRepas', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'prixKm', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'totalNuit', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'totalRepas', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'totalKm', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'total');
        }

        return array('__isInitialized__', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'autre', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'id', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'matricule', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'startDate', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'endDate', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'updateDate', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'createDate', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'online', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'valide', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'attente', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'refuser', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'qtNuit', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'qtRepas', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'qtKm', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'prixNuit', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'prixRepas', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'prixKm', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'totalNuit', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'totalRepas', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'totalKm', '' . "\0" . 'PointWeb\\FicheBundle\\Entity\\Frais' . "\0" . 'total');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Frais $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getMatricule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatricule', array());

        return parent::getMatricule();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatricule($matricule)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatricule', array($matricule));

        return parent::setMatricule($matricule);
    }

    /**
     * {@inheritDoc}
     */
    public function getQtNuit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQtNuit', array());

        return parent::getQtNuit();
    }

    /**
     * {@inheritDoc}
     */
    public function setStartDate($startDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartDate', array($startDate));

        return parent::setStartDate($startDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getStartDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartDate', array());

        return parent::getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndDate($endDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndDate', array($endDate));

        return parent::setEndDate($endDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndDate', array());

        return parent::getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setQtNuit($qtNuit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQtNuit', array($qtNuit));

        return parent::setQtNuit($qtNuit);
    }

    /**
     * {@inheritDoc}
     */
    public function setQtRepas($qtRepas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQtRepas', array($qtRepas));

        return parent::setQtRepas($qtRepas);
    }

    /**
     * {@inheritDoc}
     */
    public function getQtRepas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQtRepas', array());

        return parent::getQtRepas();
    }

    /**
     * {@inheritDoc}
     */
    public function setQtKm($qtKm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQtKm', array($qtKm));

        return parent::setQtKm($qtKm);
    }

    /**
     * {@inheritDoc}
     */
    public function getQtKm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQtKm', array());

        return parent::getQtKm();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixNuit($prixNuit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixNuit', array($prixNuit));

        return parent::setPrixNuit($prixNuit);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixNuit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixNuit', array());

        return parent::getPrixNuit();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixRepas($prixRepas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixRepas', array($prixRepas));

        return parent::setPrixRepas($prixRepas);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixRepas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixRepas', array());

        return parent::getPrixRepas();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixKm($prixKm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixKm', array($prixKm));

        return parent::setPrixKm($prixKm);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixKm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixKm', array());

        return parent::getPrixKm();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalNuit($totalNuit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalNuit', array($totalNuit));

        return parent::setTotalNuit($totalNuit);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalNuit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalNuit', array());

        return parent::getTotalNuit();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalRepas($totalRepas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalRepas', array($totalRepas));

        return parent::setTotalRepas($totalRepas);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalRepas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalRepas', array());

        return parent::getTotalRepas();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalKm($totalKm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalKm', array($totalKm));

        return parent::setTotalKm($totalKm);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalKm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalKm', array());

        return parent::getTotalKm();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotal($total)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotal', array($total));

        return parent::setTotal($total);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotal', array());

        return parent::getTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function addObjet(\PointWeb\FicheBundle\Entity\Autre $autre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addObjet', array($autre));

        return parent::addObjet($autre);
    }

    /**
     * {@inheritDoc}
     */
    public function removeObjet(\PointWeb\FicheBundle\Entity\Autre $autre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeObjet', array($autre));

        return parent::removeObjet($autre);
    }

    /**
     * {@inheritDoc}
     */
    public function getAutre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAutre', array());

        return parent::getAutre();
    }

    /**
     * {@inheritDoc}
     */
    public function setOnline($online)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOnline', array($online));

        return parent::setOnline($online);
    }

    /**
     * {@inheritDoc}
     */
    public function getOnline()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOnline', array());

        return parent::getOnline();
    }

    /**
     * {@inheritDoc}
     */
    public function setValide($valide)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValide', array($valide));

        return parent::setValide($valide);
    }

    /**
     * {@inheritDoc}
     */
    public function getValide()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValide', array());

        return parent::getValide();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttente($attente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttente', array($attente));

        return parent::setAttente($attente);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttente', array());

        return parent::getAttente();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefuser($refuser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefuser', array($refuser));

        return parent::setRefuser($refuser);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefuser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefuser', array());

        return parent::getRefuser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdateDate($updateDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdateDate', array($updateDate));

        return parent::setUpdateDate($updateDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdateDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdateDate', array());

        return parent::getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreateDate($createDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreateDate', array($createDate));

        return parent::setCreateDate($createDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreateDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreateDate', array());

        return parent::getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    public function preUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'preUpdate', array());

        return parent::preUpdate();
    }

}
